### ISSUE TITLE
Addition of pre-fetch feature before commiting

### ISSUE THREAD

**Issue by jembie** [paul1995tu/Data-Mining#1]
@paul1995tu Would it be possible to add an extension, action or anything similar for our [poetry.lock](https://github.com/paul1995tu/Data-Mining/blob/main/poetry.lock) that automatically does `git fetch` before a `git commit` is initiated? It would avoid causing future merge / git push --force situations when commits are done without any git fetch prior.

**Comment by paul1995tu** [comment]
add  touch pre-commit in .git/hooks 


#!/bin/bash

# Fetch changes from remote
git fetch

# Check if the local branch is behind the remote branch
if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then
    echo "Your branch is behind the remote branch. Please pull the latest changes before committing."
    exit 1
fi
